Add version number validation step

diff --git a/.github/workflows/pythonpublish.yml b/.github/workflows/pythonpublish.yml
--- a/.github/workflows/pythonpublish.yml
+++ b/.github/workflows/pythonpublish.yml
@@ -9,23 +9,45 @@ on:
 
 jobs:
   deploy:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python
-      uses: actions/setup-python@v1
-      with:
-        python-version: '3.x'
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install build twine
-    - name: Build and publish
-      env:
-        TWINE_USERNAME: __token__
-        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
-      run: |
-        python -m build
-        twine upload dist/*
+      - uses: actions/checkout@v2
+      - name: Get tag
+        id: vars
+        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
+      - name: Validate version number
+        run: >-
+          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
+            if ! [[ "${{ steps.vars.outputs.tag }}" =~ (a|b|rc)[0-9]+$ ]]; then
+              echo "Pre-release: Tag is missing pre-release suffix (${{ steps.vars.outputs.tag }})"
+              exit 1
+            fi
+          else
+            if [[ "${{ steps.vars.outputs.tag }}" =~ (a|b|rc)[0-9]+$ ]]; then
+              echo "Release: Tag must not have a pre-release suffix (${{ steps.vars.outputs.tag }})"
+              exit 1
+            fi
+          fi
+      - name: Validate pyproject.toml version
+        run: |
+          TOML_VERSION=$(grep -Po '(?<=^version = ")[^"]+' pyproject.toml)
+          if [[ "$TOML_VERSION" != "${{ steps.vars.outputs.tag }}" ]]; then
+            echo "Version mismatch: pyproject.toml has '$TOML_VERSION' but tag is '${{ steps.vars.outputs.tag }}'"
+            exit 1
+          fi
+      - name: Set up Python
+        uses: actions/setup-python@v1
+        with:
+          python-version: '3.x'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install build twine
+      - name: Build and publish
+        env:
+          TWINE_USERNAME: __token__
+          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
+        run: |
+          python -m build
+          twine upload dist/*
